apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-env"
  labels:
{{ include "binancechain.labels" . | indent 4 }}
type: Opaque
data:
  HOME: {{ .Values.binancechain.base_path | b64enc }}
  BNET: {{ .Values.binancechain.network | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-config"
  labels:
{{ include "binancechain.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.binancechain.configurationFileName }}: |-
  {{- include (print $.Template.BasePath "/_config.toml") . | b64enc | nindent 4 }}
  {{ .Values.binancechain.appFileName }}: |-
  {{- include (print $.Template.BasePath "/_app.toml") . | b64enc | nindent 4 }}
