{{ if .Values.externalLBp2p }}
## use this if you want to expose blockchain p2p (not RPC) to public
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb-p2p
  labels:
    chain: eth
{{ include "bsc.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  {{ if .Values.externalLBp2pIP }}
  loadBalancerIP: {{ .Values.externalLBp2pIP }}
  {{ end }}
  ports:
    - name: {{ .Values.service.p2pPortName0 }}
      port: {{ .Values.service.p2pPort0 }}
      targetPort: {{ .Values.service.p2pPortName0 }}
      protocol: {{ .Values.service.p2pPortProtocol0 }}
  selector:
    app.kubernetes.io/name: {{ include "bsc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
